module.exports = {
  USER_ROLES: {
    STUDENT: 'STUDENT',
    ADMIN: 'ADMIN',
    TNP_COORDINATOR: 'TNP_COORDINATOR',
    HOD: 'HOD',
  },

  APPLICATION_STATUS: {
    APPLIED: 'APPLIED',
    UNDER_REVIEW: 'UNDER_REVIEW',
    SHORTLISTED: 'SHORTLISTED',
    INTERVIEW_SCHEDULED: 'INTERVIEW_SCHEDULED',
    SELECTED: 'SELECTED',
    REJECTED: 'REJECTED',
    WITHDRAWN: 'WITHDRAWN',
  },

  JOB_TYPE: {
    INTERNSHIP: 'INTERNSHIP',
    FULL_TIME: 'FULL_TIME',
    BOTH: 'BOTH',
  },

  NOTIFICATION_TYPES: {
    APPLICATION_RECEIVED: 'APPLICATION_RECEIVED',
    STATUS_UPDATE: 'STATUS_UPDATE',
    NEW_OPPORTUNITY: 'NEW_OPPORTUNITY',
    DEADLINE_REMINDER: 'DEADLINE_REMINDER',
    INTERVIEW_SCHEDULED: 'INTERVIEW_SCHEDULED',
    SYSTEM: 'SYSTEM',
  },

  EMAIL_TYPES: {
    VERIFICATION: 'verification',
    PASSWORD_RESET: 'password_reset',
    APPLICATION_UPDATE: 'application_update',
    NEW_JOB: 'new_job',
  },
};
